{{- range $v := .Values.windmill.workerGroups }}
{{ if and $v.replicas (gt $v.replicas 0)}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: windmill-workers-{{ $v.name }}
  labels:
    app: windmill-workers
    app.kubernetes.io/name: windmill-workers
    chart: {{ template "windmill.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    workerGroup: {{ $v.name }}
spec:
  replicas: {{ $v.replicas }}
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  selector:
    matchLabels:
      app: windmill-workers
      workerGroup: {{ $v.name }}
  template:
    metadata:
      labels:
        app: windmill-workers
        app.kubernetes.io/name: windmill-workers
        release: {{ $.Release.Name }}
        workerGroup: {{ $v.name }}
{{- with $v.annotations }}
      annotations:
{{ toYaml . | indent 8 }}       
{{- end }}   
    spec:
      serviceAccountName: {{ template "windmill.serviceAccountName" $ }}
      containers:
      - name: windmill-worker
       {{ if  $.Values.enterprise.nsjail }}
       #because nsjail requires privileged access
        securityContext:
          privileged: true
        {{ else }}
        securityContext:
          runAsUser: 0
        {{end}}
        {{ if $.Values.enterprise.enabled }}
        image: {{ default "ghcr.io/windmill-labs/windmill-ee" $.Values.windmill.image }}:{{ default $.Chart.AppVersion $.Values.windmill.tag }}
        {{ else }}
        image: {{ default "ghcr.io/windmill-labs/windmill" $.Values.windmill.image }}:{{ default $.Chart.AppVersion $.Values.windmill.tag }}
        {{ end }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        - containerPort: 8001
        env:
        {{- with $v.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{ if $.Values.enterprise.enabled }}
        - name : "METRICS_ADDR"
          value: "true"
        {{ end }}
        - name: "DATABASE_URL"
          value: "{{ $.Values.windmill.databaseUrl }}"
        - name: "BASE_URL"
          value: "{{ $.Values.windmill.baseProtocol }}://{{ $.Values.windmill.baseDomain }}"
        - name: "RUST_LOG"
          value: "{{ $.Values.windmill.rustLog }}"
        - name: "NUM_WORKERS"
          value: "1"
        - name: "DISABLE_SERVER"
          value: "true"
        - name: "JSON_FMT"
          value: "true"
        {{ if $.Values.windmill.pipIndexUrl }}
        - name: "PIP_INDEX_URL"
          value: "{{ $.Values.windmill.pipIndexUrl }}"
        {{ end }}
        {{ if $.Values.windmill.pipExtraIndexUrl }}
        - name: "PIP_EXTRA_INDEX_URL"
          value: "{{ $.Values.windmill.pipExtraIndexUrl }}"
        {{ end }}
        {{ if $.Values.windmill.globalErrorHandlerPath }}
        - name: "GLOBAL_ERROR_HANDLER_PATH_IN_ADMINS_WORKSPACE"
          value: "{{ $.Values.windmill.globalErrorHandlerPath }}"
        {{ end }}
        {{ if $.Values.windmill.pipTrustedHost }}
        - name: "PIP_TRUSTED_HOST"
          value: "{{ $.Values.windmill.pipTrustedHost }}"
        {{ end }}
        {{ if $.Values.windmill.denoExtraImportMap }}
        - name: "DENO_EXTRA_IMPORT_MAP"
          value: "{{ $.Values.windmill.denoExtraImportMap }}"
        {{ end }}
        {{ if $.Values.windmill.npmConfigRegistry }}
        - name: "NPM_CONFIG_REGISTRY"
          value: "{{ $.Values.windmill.npmConfigRegistry }}"
        {{ end }}
        {{ if $.Values.enterprise.enabled }}
        - name: "LICENSE_KEY"
          value: "{{ $.Values.enterprise.licenseKey }}"
        {{ if $.Values.enterprise.enabledS3DistributedCache }}
        - name: "S3_CACHE_BUCKET"
          value: "{{ .Values.enterprise.s3CacheBucket }}"
        - name: "RCLONE_S3_PROVIDER"
          value: "AWS"
        {{ end }}
        {{ if $.Values.enterprise.nsjail }}
        - name: "DISABLE_NSJAIL"
          value: "false"
        {{ end }}
        {{ end }}
        - name: "WORKER_TAGS"
          value: "{{ $v.name }}"
        resources:
{{ toYaml $v.resources | indent 12 }}
      volumes:
      - name: oauth-volume
        secret:
          secretName: {{ if $.Values.windmill.oauthSecretName }}{{ $.Values.windmill.oauthSecretName }}{{ else }} {{ $.Release.Name }}-oauth-secret {{- end }}
    {{ if $.Values.windmill.exposeHostDocker }}
      - name: docker-sock
        hostPath:
          path: "/var/run/docker.sock"
          type: File
    {{ end }}
    {{- with $v.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with $v.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with $v.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}    
{{- end }}
{{- end }}
